#!/usr/bin/env bash
# ------------------------------------------------------------------------------
# TITLE   : Golden-file tests for scripts/mc_friction_process_entries.awk
# PURPOSE : Characterize the friction awk backend: entry routing (stdout /
#           archive_file), preamble passthrough, exact vs prefix project
#           matching, the exclusive before_date boundary, stale flagging, and
#           malformed handling. stdout and archive contents are compared byte
#           for byte against committed golden files; summary counts on stderr
#           are asserted with targeted string checks (the histogram/percentage
#           formatting is an unspecified implementation detail and is not
#           goldened, which also keeps the goldens awk-implementation
#           independent). Exits nonzero on any failure.
# USAGE   : bash bash/test/friction_awk.sh
# NOTES   : The awk script is invoked exactly as bash/13_friction.sh invokes it
#           (`awk -f <script>`), and is treated as read-only. Golden files were
#           generated by running the script on the committed input fixtures and
#           hand-verified against the script's own header spec before commit.
# ------------------------------------------------------------------------------
set -u

test_directory="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
repo_root="$(cd "$test_directory/../.." && pwd)"

awk_script="$repo_root/scripts/mc_friction_process_entries.awk"
fixtures="$test_directory/fixtures/friction"
expected="$fixtures/expected"
basic="$fixtures/entries_basic.txt"
malformed="$fixtures/entries_malformed.txt"

sandbox="$(mktemp -d)"
trap 'rm -rf "$sandbox"' EXIT

# --- Assertion helpers --------------------------------------------------------
tests_run=0
tests_failed=0

check() {   # check <description> <expected> <actual>
    tests_run=$((tests_run + 1))
    if [[ "$2" == "$3" ]]; then
        printf '  ok   %s\n' "$1"
    else
        printf '  FAIL %s (expected [%s], got [%s])\n' "$1" "$2" "$3"
        tests_failed=$((tests_failed + 1))
    fi
}

golden() {  # golden <description> <expected_file> <actual_file>
    tests_run=$((tests_run + 1))
    local diff_output
    if diff_output="$(diff -u "$2" "$3" 2>&1)"; then
        printf '  ok   %s\n' "$1"
    else
        printf '  FAIL %s\n%s\n' "$1" "$diff_output"
        tests_failed=$((tests_failed + 1))
    fi
}

contains() { grep -qF -- "$2" <<< "$1" && printf 'yes' || printf 'no'; }

# ==============================================================================
# 1. show, no filter  -> every entry + preamble, in input order
# ==============================================================================
printf '\n--- show (no filter) ---\n'
awk -f "$awk_script" -v mode=show "$basic" > "$sandbox/1.out" 2> "$sandbox/1.err"
golden "show no-filter stdout matches golden" "$expected/show_all.stdout" "$sandbox/1.out"
check "show no-filter reports 5 entries total" "yes" "$(contains "$(cat "$sandbox/1.err")" "friction: 5 entries total")"

# ==============================================================================
# 2. show, exact project=web  -> only the literal "web" entries
# ==============================================================================
printf '\n--- show (exact project=web) ---\n'
awk -f "$awk_script" -v mode=show -v project=web -v match_mode=exact "$basic" > "$sandbox/2.out" 2>/dev/null
golden "show exact stdout matches golden (no web-auth, no website)" "$expected/show_exact_web.stdout" "$sandbox/2.out"

# ==============================================================================
# 3. show, prefix project=web  -> "web" and "web-*" subtopics, not "website"
# ==============================================================================
printf '\n--- show (prefix project=web) ---\n'
awk -f "$awk_script" -v mode=show -v project=web -v match_mode=prefix "$basic" > "$sandbox/3.out" 2>/dev/null
golden "show prefix stdout matches golden (web + web-auth, not website)" "$expected/show_prefix_web.stdout" "$sandbox/3.out"

# ==============================================================================
# 4. show, stale_before  -> entries strictly older than the cutoff are flagged
# ==============================================================================
printf '\n--- show (stale_before) ---\n'
# `today` is accepted by the script but currently unused; passed here to
# document the documented interface. Stale set is driven solely by stale_before.
awk -f "$awk_script" -v mode=show -v stale_before=2026-03-01 -v today=2026-03-20 \
    "$basic" > "$sandbox/4.out" 2> "$sandbox/4.err"
golden "stale run leaves stdout identical to no-filter show" "$expected/show_all.stdout" "$sandbox/4.out"
stale_err="$(cat "$sandbox/4.err")"
check "stale summary reports 2 stale entries" "yes" "$(contains "$stale_err" "stale (>14 days): 2 entries")"
check "stale list names 2026-01-05 web"       "yes" "$(contains "$stale_err" "2026-01-05 web")"
check "stale list names 2026-02-10 web-auth"  "yes" "$(contains "$stale_err" "2026-02-10 web-auth")"
check "boundary-day 2026-03-01 is not stale"  "no"  "$(contains "$stale_err" "2026-03-01 web")"

# ==============================================================================
# 5. archive project=web (prefix) before_date=2026-03-01
#    matched (web-domain AND before cutoff) -> archive_file; rest -> stdout
# ==============================================================================
printf '\n--- archive (project=web, before_date=2026-03-01) ---\n'
archive_out="$sandbox/archive.archived"
rm -f "$archive_out"    # awk appends (>>); start from absent for a clean golden
awk -f "$awk_script" -v mode=archive -v project=web -v match_mode=prefix \
    -v before_date=2026-03-01 -v archive_file="$archive_out" \
    "$basic" > "$sandbox/5.out" 2> "$sandbox/5.err"
golden "archive remainder (stdout) matches golden" "$expected/archive_web.stdout" "$sandbox/5.out"
golden "archived entries (file) match golden"      "$expected/archive_web.archived" "$archive_out"
archive_err="$(cat "$sandbox/5.err")"
check "archive summary: 2 archived (project:web, before cutoff)" "yes" \
    "$(contains "$archive_err" "archived: 2 entries (project:web, before 2026-03-01)")"
check "archive summary: 3 remaining" "yes" "$(contains "$archive_err" "remaining: 3 entries")"

# ==============================================================================
# 6. malformed entries: warned + counted, but still routed to stdout
# ==============================================================================
printf '\n--- malformed handling ---\n'
awk -f "$awk_script" -v mode=show "$malformed" > "$sandbox/6.out" 2> "$sandbox/6.err"
golden "malformed entries still pass through to stdout" "$expected/malformed.stdout" "$sandbox/6.out"
malformed_err="$(cat "$sandbox/6.err")"
malformed_warns="$(grep 'malformed entry:' "$sandbox/6.err" || true)"
check "exactly one malformed entry reported" "yes" "$(contains "$malformed_err" "friction[WARN]: 1 malformed entries")"
check "the missing-project entry is flagged" "yes" "$(contains "$malformed_warns" "noproject here")"
# The date validation is format-only (4-2-2 digits); an impossible-but-well-
# formed date is NOT flagged as malformed. Recorded as a finding.
check "impossible-but-well-formed date is NOT flagged malformed" "no" \
    "$(contains "$malformed_warns" "2026-13-99")"

# --- Summary ------------------------------------------------------------------
printf '\n[friction_awk] %d run, %d failed\n' "$tests_run" "$tests_failed"
[[ "$tests_failed" -eq 0 ]]
