# Dealing with Dropbox Update
## Introduction
On January 06, 2025, Dropbox performed an update to its folder structure. This update changed the folder location of my dropbox files, in particular, scripts that analyze my saved data and how zotero knows where to move files and how to find them.
The folder locations went from:
C:\Users\Luis\Dropbox (MIT)
to
C:\Users\Luis\MIT Dropbox\Luis Martinez
## Solution
Two settings have to be changed to deal with the update.
First, go to Edit > Settings > Advanced > Files and Folders > Linked Attachment Base Directory > Base Directory.
If you have attanger plugin, then after Settings go to Attanger plugin, change Destination Path Root Directory.

When you update the Linked Attachment Base Directory, it can take a while to detect all of the files under the folder. Be patient.

Everything should be good after these changes.
If you want, the old directory should still be available and have some of the downloaded files. This can be backed up before any changes.
