---
title: Neovim development setup
---

This documents contains the instructions for installing neovim and some additional dependencies required for my configuration.

## Install neovim kickstart, quarto, and zotero

Install treesitter cli binary
```{bash}
wget https://github.com/tree-sitter/tree-sitter/releases/download/v0.22.6/tree-sitter-linux-x64.gz
gunzip tree-sitter-linux-x64.gz
chmod +x tree-sitter-linux-x64
mv tree-sitter-linux-x64 /usr/local/bin/tree-sitter
```
If you installed some treesitter libraries that you dont need, remove them from the treesitter.lua file and uninstall them using :TSUninstall {lang}.

Install nodejs
```{bash}
apt install npm
```
or from source
```{bash}
wget https://nodejs.org/dist/latest/node-v22.5.1-linux-x64.tar.gz
tar xzvf node-v22.5.1-linux-x64.tar.gz
cd node-v22.5.1-linux-x64
export PATH=$PATH:~/node-v22.5.1-linux-x64/bin
```
This is required for the latex treesitter.

## Install neovim
Download most recent neovim release, decompress and create symbolic link.
```{bash}
curl -L -o nvim-linux64.tar.gz https://github.com/neovim/neovim/releases/download/stable/nvim-linux64.tar.gz
tar -xzvf nvim-linux64.tar.gz
sudo ln -s ~/nvim-linux64/bin/nvim /usr/local/bin/nvim
```
If you are working on a server that allows you to install software and the symbolic link is not pointing corretly, then you can edit your .bashrc file to create an alias to nvim.
If you have already downloaded and unzipped neovim previously, only the first two steps are required. Probably could setup a cron job to update automatically.
Run neovim command $nvim to confirm that "installation" was succesful.

## Update neovim
Remove the old version and symlink.
```{bash}
rm -rf nvim-linux64
sudo rm /usr/local/bin/nvim
INSTALLATION_DIRECTORY="$HOME/.local/share/nvim/"
NEOVIM_VERSION="0.11.2"
mkdir -p "${INSTALLATION_DIRECTORY}"
curl -L -o nvim-linux-x86-64.tar.gz https://github.com/neovim/neovim/releases/download/v0.11.2/nvim-linux-x86_64.tar.gz
tar -xzvf nvim-linux-x86-64.tar.gz -C "$INSTALLATION_DIRECTORY"
sudo ln -s ${INSTALLATION_DIRECTORY}nvim-linux-x86_64/bin/nvim /usr/local/bin/nvim
nvim --version
```

## Before cloning neovim configuration
This neovim config is meant to be used with the my_config directory to manage my dotfiles and neovim configuration in one repository. (for now)

This requires you to setup symbolic links from this repository to the ~/.config/nvim folder.
Create the my_config directory. Move the different files to the my_config directory then create the symbolic links. There is one example below.
```{bash}
mkdir my_config
mv ~/.config/nvim ~/my_config/nvim
ln -s ~/my_config/nvim ~/.config/
```
Use git status to check that the files within the nvim directory are now part of the my_config directory. When first cloned, the nvim directory is treated as a submodule. This could be useful for some.

Run checkhealth to see errors for any plugins and run :Lazy and U to update plugins.

## Alternative vimrc file
I also have a vimrc file with a pretty minimal set of options enabled that I can use in my institution's linux cluster since I dont want to mess around with installing a lot of files to be able to use my neovim configuration there.
```{bash}
rm ~/.vimrc # if there is a file there
ln -s ~/my_config/dotfiles/vimrc ~/.vimrc
```

See (alternative-neovim-configurations)[alternative-neovim-configurations.md] file to look at other useful installations.
I have not extensively tested the distributions below but from my quick impressions, the LazyNvim distribution seems to be the best out-of-the-box that balances completeness but also extensibility.

## Errors encountered

### Tree-sitter r_language_server lsp
Mason was giving me errors during installation of the r-languageserver.
To see how I resolved the issue, look at the -- R r-languageserver section and 001_setupR directory from my lab_utils repository.
Briefly, I installed r-languageserver via R using install.packages() and then setup the r-languageserver by itself in the lsp.lua config file.
This way, Mason doesnt try to install it everytime I open Neovim.
